[versions]
agp = "8.13.2"
kotlin = "2.3.10"
kotlinxDatetime = "0.7.1"
coreKtx = "1.17.0"
junit = "5.14.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeBom = "2026.01.01"
koin-bom = "4.1.1"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"
kotlinSerialization = "2.3.10"
mockk = "1.14.9"
kotlinxCoroutines = "1.10.2"
desugar = "2.1.5"
room = "2.8.4"
ksp = "2.3.4"
ktor = "3.4.0"
supabase = "3.3.0"
junitJunit = "4.13.2"
robolectric = "4.16.1"
playServicesLocation = "21.3.0"
rules = "1.7.0"
kotlinFaker = "1.16.0"
slf4j = "2.0.17" # Logger
turbine = "1.2.1"
testCore = "1.7.0"
testRunner = "1.7.0"
testRules = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version = "kotlinxCoroutines" }

# AndroidX test
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "testCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }

# Koin
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-bom" }
koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koin-bom" }
# Navigation 3
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

#Ktor
io-ktor-client = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
io-ktor-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
io-ktor-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

#Kotlin Faker
kotlin-faker = { group = "io.github.serpro69", name = "kotlin-faker", version.ref = "kotlinFaker" }

#RoboElectric
roboelectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# SLF4J Logger
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }

desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

#Kotlinx-Datetime
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Testing
io-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

#Supabase
supbase-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version.ref = "supabase" }
supbase-postgres = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt" }
supbase-auth = { group = "io.github.jan-tennert.supabase", name = "auth-kt" }
supbase-realtime = { group = "io.github.jan-tennert.supabase", name = "realtime-kt" }

# Junit
junit-junit = { group = "junit", name = "junit", version.ref = "junitJunit" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
